# Generated by Django 5.0.6 on 2024-05-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_details',
            fields=[
                ('candidate_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=50)),
                ('University_name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=50)),
                ('YOP', models.DateField()),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'candidate_data',
            },
        ),
    ]
